### ISSUE TITLE
Mopidy support

### ISSUE THREAD

**Issue by iacs** [mierak/rmpc#179]
### Description

I didn't see in the docs any mention of mopidy compatibility. Is it supposed to work with mopidy?

I couldn't get a connection going when I tried it

**Comment by mierak** [comment]
It should work somewhat. Rmpc does not officially support mopidy, because its MPD protocol implementation is very old and `mopidy-mpd` is basically unmaintained. You can check the issue here https://github.com/mopidy/mopidy-mpd/issues/68.
Anyway, even if you manage to make rmpc connect to mopidy, there will most likely be unexpected side effects, errors and album art will simply not work at all, sorry :(
