### ISSUE TITLE
Add fedora package manager support

### ISSUE THREAD

**Issue by mecattaf** [mierak/rmpc#32]
Hi @mierak first of all thanks for creating this awesome package! Truly the spiritual successor to ncmpcpp with album artwork we were all waiting for :1st_place_medal: 

I run fedora, and prefer installing system packages through the package manager rather than rust crates. I tried adding [the following PR](https://github.com/solopasha/hyprlandRPM/pull/29) to a popular COPR repository that has lots of useful wayland-related utilities but the code is not functional and the maintainer is not interested in helping out. So I thought I would ask the creator of the package directly. 

Would you be willing to package your `rmpc` for fedora? Ideally through the package manager or alternatively through a COPR that can track the future changes?

All best,
Tom

**Comment by mierak** [comment]
Hi, thank you for your kind words!

I would be more than happy to have rmpc available for Fedora(and other systems for that matter), but I do not think I am the right person to maintain such package since I personally use Arch and never touched Fedora itself.

I can help with getting rmpc to build if that is an issue though.
