### ISSUE TITLE
Configurable tab bar and add "Album Artist" tab

### ISSUE THREAD

**Issue by AleryBerry** [mierak/rmpc#60]
I think we need to be able to edit the tab bar in a way that you could exclude some tabs from view and rearrange them. e.g. I want to only see "Queue | Artist" in the tab bar.
Also I would like to use an "Album Artist" tab because not always tracks are properly tagged using Artist.
I'm loving this project so far btw!

**Comment by mierak** [comment]
Hi, I am glad you are enjoying rmpc!
I am currently working on a feature that will allow you to do just that. I want to make tabs completely configurable, including merging two or more tabs into one. I am still figuring out how to do things the right way so it may take some time to finish.

For the Album Artist, I want to do that as well, just not sure what the right way to go about this is. Should we make it somehow configurable, add a new tab since they are going to be configurable anyway or just simply swap `artist` for `albumartist`. Simply swapping them should be fine, MPD  falls back to `artist` if `albumartist` is not present anyway, but I am leaning towards adding a new tab.

**Comment by mierak** [comment]
Hi, this is resolved with the merge of https://github.com/mierak/rmpc/pull/61. You can get your desired behavior by configuring [tabs](https://mierak.github.io/rmpc/configuration/tabs/). It is now possible to reorder, rename and remove tabs as well as combine more panes(what were previously tabs are now called panes) into one.
I have also added an `AlbumArtists` pane to address your second point.

This config should get you what you want:
```rust
tabs: [
    (
        name: "Queue",
        border_type: None,
        pane: Split(
            direction: Horizontal,
            panes: [
                (
                    size: "40%",
                    pane: Pane(AlbumArt),
                ),
                (
                    size: "60%",
                    pane: Pane(Queue),
                ),
            ],
        ),
    ),
    (
        name: "Artists",
        border_type: None,
        pane: Pane(AlbumArtists),
    ),
],
```

Please let me know if you have any issues!
