### ISSUE TITLE
Consider each Playlist as separate standalone queue

### ISSUE THREAD

**Issue by Solarunit** [mierak/rmpc#80]
Ignore main Queue and consider each Playlists as separate standalone queue.
I wonder could this concept that is used in some other players be implemented in this mpd client? No other mpd clients can do this, and I am no sure if it's limitation of mpd server.

The concept is this:
 - each playlist has separate standalone queue
 - you can switch between playlists and it should remember the last playing song in this playlist

The good example of such player is tauon.

**Comment by mierak** [comment]
I would like a feature similar to this myself, however, there is a reason why no MPD client has a feature like this, and thats because MPD only has concept of a single active queue and multiple stored playlists.
Keeping state like what song was last playing in a stored playlist in rmpc is fragile and prone to state desync with the mpd server. For example when stored playlist changes or gets deleted when rmpc is not running, or the mount with the song gets unmounted and plethora of others. So unless I can somehow come up with robust enough solution, this will sadly not happen.

**Comment by Solarunit** [comment]
Yea, that's unfortunate that mpd doesn't support such feature :face_with_diagonal_mouth:

**Comment by Solarunit** [comment]
@mierak I recently had discussion with mpd dev about Multiple playlists support, if you're interested: https://github.com/MusicPlayerDaemon/MPD/issues/2317

**Comment by mierak** [comment]
I have read that, actually. I still don't think that keeping what song was last played for each stored playlist is viable strategy. But for the "I want to select song from a playlist and it replaces the whole queue and starts playing from that song" thing, it should be solved along with this https://github.com/mierak/rmpc/issues/400

**Comment by Solarunit** [comment]
>I still don't think that keeping what song was last played for each stored playlist is viable strategy.

Well that's expected in all playlist-based players because you can freely switch between playlists on the fly.
But I understand that mpd was designed a certain way and has limitations..

>But for the "I want to select song from a playlist and it replaces the whole queue and starts playing from that song" thing, it should be solved along with this https://github.com/mierak/rmpc/issues/400

Yes, this should improve usability with loading playlist a lot! Gonna subscribe to that thread.
